# Generated by Django 4.1.1 on 2022-09-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0002_alter_music_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AddField(
            model_name='music',
            name='bass_player',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.CharField(default='5:00', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='finished_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='guitar_player',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='keyboarder',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='mixer',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='producer',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='recorder',
            field=models.CharField(default='Zhixun Teng', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='music_title', max_length=100, primary_key=True, serialize=False),
        ),
    ]
