# Generated by Django 4.1.1 on 2022-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0003_remove_music_id_music_bass_player_music_composer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
