# Generated by Django 4.1.1 on 2022-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0004_music_cover_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTV',
            fields=[
                ('video_file', models.FileField(upload_to='')),
                ('cover_file', models.ImageField(upload_to='')),
                ('finished_date_time', models.DateTimeField(null=True)),
                ('title', models.CharField(default='music_title', max_length=100, primary_key=True, serialize=False)),
                ('camera_oprator', models.CharField(default='Zhixun Teng', max_length=100)),
                ('editor', models.CharField(default='Zhixun Teng', max_length=100)),
                ('director', models.CharField(default='Zhixun Teng', max_length=100)),
                ('lighting_operator', models.CharField(default='Zhixun Teng', max_length=100)),
            ],
        ),
    ]
