# Generated by Django 4.1.1 on 2022-09-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0006_image_me_alter_mtv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_me',
            name='title',
            field=models.CharField(default='iamge_me_title', max_length=100, primary_key=True, serialize=False),
        ),
    ]
