# Generated by Django 4.1.1 on 2022-09-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0007_alter_image_me_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_me',
            name='edited_finished_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_me',
            name='title',
            field=models.CharField(default='image_me_title', max_length=100, primary_key=True, serialize=False),
        ),
    ]
