# Generated by Django 4.1.1 on 2022-09-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0008_alter_image_me_edited_finished_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Shooting',
            fields=[
                ('image_file', models.ImageField(upload_to='')),
                ('title', models.CharField(default='image_shooting_title', max_length=100, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200, null=True)),
                ('age', models.FloatField(blank=True)),
                ('created_date_time', models.DateTimeField()),
                ('edited_finished_date_time', models.DateTimeField(blank=True, null=True)),
                ('mindflow', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
