# Generated by Django 4.1.1 on 2022-09-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0009_image_shooting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('title', models.CharField(default='image_shooting_title', max_length=100, primary_key=True, serialize=False)),
                ('aim', models.CharField(max_length=500, null=True)),
                ('reason', models.CharField(max_length=700, null=True)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
