# Generated by Django 4.1.1 on 2022-09-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0010_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now',
            name='title',
            field=models.CharField(default='now_title', max_length=100, primary_key=True, serialize=False),
        ),
    ]
