# Generated by Django 4.1.1 on 2022-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0011_alter_now_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('title', models.CharField(default='now_title', max_length=100, primary_key=True, serialize=False)),
                ('date_and_year', models.DateTimeField()),
                ('age', models.FloatField()),
                ('event', models.CharField(max_length=500)),
                ('mindflow', models.CharField(max_length=500)),
                ('people', models.CharField(max_length=200)),
            ],
        ),
    ]
