# Generated by Django 4.1.1 on 2022-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0014_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('title', models.CharField(default='education_title', max_length=100, primary_key=True, serialize=False)),
                ('acquirement', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=500)),
                ('date_and_year', models.DateTimeField()),
            ],
        ),
    ]
