# Generated by Django 4.1.1 on 2022-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0015_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('company', models.CharField(default='company', max_length=50, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
                ('job_title', models.CharField(max_length=50)),
                ('duty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
